import React from "react";

const tableData = [
  {
    id: "01",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "02",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "03",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "04",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "05",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "06",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "07",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "08",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "09",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "10",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "11",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "12",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "13",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "14",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "15",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "16",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "17",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "18",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "19",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "20",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "21",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "22",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "23",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "24",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "25",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "26",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "27",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "28",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "29",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "30",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "31",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
  {
    id: "32",
    firstName: "Krishna",
    lastName: "Chaudhary",
    Email: "ch.krishnakumar01@outlook.com",
    Language: "English",
  },
];

export default tableData;
